### ISSUE TITLE
Previous Region in Twitter posting

### ISSUE THREAD

**Issue by CaptWakaWaka** [bunzosteele/PokeWatch#55] opened 2016-07-30 14:42 UTC
Just set this up yesterday (with the 70m radius) on an AWS host and working quite well -- thank you!

The only issue I've noticed is sometimes a twitter post will contain the correct coordinates for the pokemon, but will be using the text of the previous (incorrect) region.  That is to say, the location checked just prior to the current location was in a different region.  Perhaps there is a lag on server response announcing found pokemon and it is being processed during the next location search in pokewatch?

**Comment by bunzosteele** [comment] 2016-07-30 18:12
This can be caused by one of 3 things:

A typo in your Configuration.json (wrong gps cordinates in a region, or wrong region name for gps coordinates).
Having two bots run using the same PTC/Google account.
A client bug that I have now fixed but have not yet released a V3 download for, this will be released sometime today.

**Comment by bunzosteele** [comment] 2016-07-30 21:27
Releasing fix for client bug momentarily

**Closed as completed by bunzosteele** 2016-07-30 21:27 UTC
